### ISSUE TITLE
Design system anchors

### ISSUE THREAD

**Issue by allanaw** [unimelb/unimelb-design-system#778] opened 2017-01-12 23:55 UTC
Using anchors in the design system, I would expect the landing area to include the line that the anchor is on.

Eg. If I'm anchoring to the '[STAR model](https://cms.unimelb.edu.au/controlled-environment/careers/students/applying-for-work/application-forms#STAR)' content, I add the anchor name within the H2 of the section so the user can see heading (if applicable) when they land in the target area.

This is a visual of what I expect to see with an anchor in the heading tag:
![anchor-should-be](https://cloud.githubusercontent.com/assets/23711960/21913022/cd38c64e-d97d-11e6-9305-f26e82df1a03.jpg)

This is how the anchor in the heading tag is currently displaying (heading not visible):
![anchor-actual](https://cloud.githubusercontent.com/assets/23711960/21913076/2540b018-d97e-11e6-9f83-8d669c8aae77.jpg)

I have tried both:
```
<h2 id="STAR">The STAR model</h2>
<h2><a name="STAR">The STAR model</h2>
```

Web path:
https://cms.unimelb.edu.au/controlled-environment/careers/students/applying-for-work/application-forms#STAR

Is this something that can be changed at my end (placement of the anchor tag), or is this an anchor bug?

Thanks,
Allana

**Comment by axelboc** [comment] 2017-01-13 00:20
This is caused by the fixed navigation bar at the top of the screen. The browser doesn't know about it when it scrolls down to the anchor.

Before I move on to potential solutions, please note that the recommended way to create an anchor is to use the `id` attribute (on any element), rather than to create an empty anchor with a `name` attribute. It's also recommended to use lower case. So in your case, I would recommend using:

```
<h2 id="star">The STAR model</h2>
```

Now, ideally, to work around your issue you would need to make sure that the `h2` has a `padding-top` value greater than the height of the navigation bar. So if the navigation bar is 60px-tall, you could try setting `padding-top: 70px;` on the `h2`. The problem is that the design system uses bottom padding for spacing, so by doing the above you would considerably increase the spacing between your heading and the paragraph that precedes it.

Another solution would be to wrap your heading and the content that follows inside a container that includes its own padding, and to move the anchor (i.e. the `id`) to that container. For instance, a section with class `alt` would do the trick, but comes with its own styling (a slightly gray background):

```
<section id="star" class="alt">
  <h2>The STAR model</h2>
  ...
</section>
```

The last solution I have in mind is a last resort. I'm not 100% sure it would work, but you could try adding your anchor to the end of the preceding paragraph:

```
<p>...<span id="star"></span></p>
<h2>The STAR model</h2>
```

**Comment by yevek** [comment] 2017-01-17 01:33
Hi @allanaw if you turn the jump nav on (via metadata screen) for that page it will fix the issue you are having. That page is long enough that it justifies using the jump nav.

![jumpnav](https://cloud.githubusercontent.com/assets/1305804/22004607/2b0012ec-dcb1-11e6-8c29-d9af54893779.png)

**Comment by axelboc** [comment] 2017-02-06 02:12
Okay, closing this issue now. @allanaw, feel free to re-open it if needed.

**Closed by axelboc** 2017-02-06 02:12 UTC
